FROM node:18-alpine

RUN apk add --no-cache --virtual .build-deps \
	ca-certificates \
	wget \
	tar && \
	cd /usr/local/bin && \
	wget https://yarnpkg.com/latest.tar.gz && \
	tar zvxf latest.tar.gz && \
	ln -s /usr/local/bin/dist/bin/yarn.js /usr/local/bin/yarn.js && \
	apk del .build-deps

WORKDIR /app

COPY ./packages/angular-v12 /app
COPY ./tsconfig.json /app/tsconfig.json

RUN rm /app/yarn.lock
RUN rm -rf /app/node_modules

RUN yarn install

CMD ["yarn", "test"]